### ISSUE TITLE
Are contributions allowed?

### ISSUE THREAD

**Issue by IamRaviTejaG** [palash25/Notes#3]
Are you open to contributions on this repo?

**Comment by IamRaviTejaG** [comment]
@palash25 Bol na?!

**Comment by palash25** [comment]
No this is my personal stuff but you are free to fork it and add your own but please don't make a PR.

**Comment by palash25** [comment]
No this is my personal stuff but you are free to fork it and add your own but please don't make a PR.

Atlough I might be accepting PRs in the future but not now.

**Comment by IamRaviTejaG** [comment]
Sure. 😄
